version: "3"

services:
  mysql:
    image: mariadb
    ports:
      - "8306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html:rw"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_USE_THEMES', false );

  wp-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    volumes:
      - ./src:/var/www/html:rw
      - ./bin/install-wp.sh:/usr/local/bin/install-wp:ro
    command: "wp --info"
