version: "3"

services:
  mysql:
    image: mariadb
    ports:
      - "8306:3306"
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"

  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    volumes:
      - "./wordpress:/var/www/html:rw"
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DEBUG: 1

  wp-cli:
    image: wordpress:cli
    depends_on:
      - wordpress
    volumes:
      - "./wordpress:/var/www/html:rw"
      - "./bin/install-wordpress.sh:/usr/local/bin/install-wordpress:ro"
      - "./bin/install-packages.sh:/usr/local/bin/install-packages:ro"
    command: "--info"

  composer:
    image: composer
    volumes:
      - "./wordpress:/var/www/html:rw"

  phpunit:
    image: phpunit/phpunit
    volumes:
      - "./wordpress:/app:ro"
